{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.datasets import load_iris\n",
    "from sklearn.cluster import DBSCAN\n",
    "from sklearn.decomposition import PCA\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import Iris dataset to play with\n",
    "iris = load_iris()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Compute DBSCAN using Iris dataset\n",
    "dbscan = DBSCAN()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "DBSCAN(algorithm='auto', eps=0.5, leaf_size=30, metric='euclidean',\n",
       "    metric_params=None, min_samples=5, n_jobs=None, p=None)"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dbscan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "DBSCAN(algorithm='auto', eps=0.5, leaf_size=30, metric='euclidean',\n",
       "    metric_params=None, min_samples=5, n_jobs=None, p=None)"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dbscan.fit(iris.data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,\n",
       "        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,\n",
       "        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,\n",
       "        1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,\n",
       "       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,\n",
       "        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,\n",
       "        1,  1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,\n",
       "        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1, -1,\n",
       "        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],\n",
       "      dtype=int64)"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# We can observe that there are 3 different values\n",
    "# Here, 0 & 1 are 2 clusters observed by the algorithm\n",
    "# -1 represents noise\n",
    "dbscan.labels_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAX8AAAEICAYAAAC3Y/QeAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvOIA7rQAAIABJREFUeJzt3XmcFeWV8PHfoWmhBW0UCaMCDVGjsokRjEHzQiSJa9w1SrPpOAzBJSSEbAxRcEgY40TEJQQHFbFd0OhoAr6aRXB8dSIQm0WQhCibKzahFQQF+rx/VBXcvl13r3urqu/5fj73c7e6VU9d6HOfepbziKpijDGmvLQJuwDGGGNKz4K/McaUIQv+xhhThiz4G2NMGbLgb4wxZciCvzHGlCEL/qakxHG/iPxDRF4Vka+IyLoC9qcicmyQZczh2GNE5KUwjh0FIjJURLYUYb89RGSHiFQEvW9zgAX/iBKRDSKyS0Q+FpHtIvKyiIwTkTYJ2zwgIp+5fygfi8hyERmS8P5BIvKfIrLF3eYtEbk96TjDRWSZ+/67IvKsiJyRtM0YN8hekfT6UPf1u5Nef0lExqQ4tTOArwPdVPVUVf0fVT0+v28pPyJynlvG7SLynojcKyKHlLIMSeUJ7QcsilR1k6p2VNV9YZelNbPgH23fVNVDgBpgBvBDYG7SNreqakegGvgV8GRCjenHwEDgVOAQ4KvAa94HReR7wEzgZ0BXoAdwD3Bh0jFGA9vc+2Q7gVEi0jPLc6oBNqjqziy3L4Zq4N+Bo4ATgW7AL0IsT95EpG3YZTAxpap2i+AN2AB8Lem1U4EmoK/7/AHg3xPePxhQ4Cj3+e+ACSn2Xw3sAC7PUI4a95iXAnuBrgnvDQW2AHcC9ye8/hIwxmdf/wzsBva5x57q7SPpvL8PrAQagceA9gnvTwLeBd4BrnHP91j3vXOBNcDHwNvA97P8ri8BVqV5vzvwJLAVaADucl8fA7zkPu7plqVtwucWA9e6j48Flrjn9CHwmPv6i+7ndrrfybfc188H6oHtwMtA/6Tv6Ifud/Qp0NZ9/rZ77uuAYSnO5TycCsBHwGbg5oT3vHMYDWxyyzk54f0q9//cP9zveVLiv53PsRQYB/zN/czdgLjvtQH+DdgIfAA8CFT7fZfu9/yme25vAbUJx7gGWOvu/zmgJuy/3bjcQi+A3VL8w/gEf/f1TcC33ccP4AZ/oML9Q3sTqHBf+zd3+/FAP+8Pz33vbJxg3jZDOaYAr7qPVwHfS3hvKE7w/yc3mBzvvu4b/N33xuAGzMR9JJ33qzi18sPdP+xxCWV+H+gLdAAepnnwfxf4ivv4MOCLWX7XM4FHU7xXAawAbneP2R44I/lckgOW+9piDgT/R4DJbtDbvw/3vf3n4D7/ohsQv+Qef7T7vbRL+I7qcX6UqoDjcQL5UQllOSbF+Qx1/y+0Afq73+dFSedwr7vfk3B+XE50358B/I/779IdWE3m4P87oBPOVeVW4Gz3vWuA9cDngY44P67zk79L9ztP/L91JNDHfXyRu48T3W3/DXg57L/duNys2Sd+3sH54/N8X0S249QcZwJT9EBb6c+B/wBqgWXA2yLiNd10Bj5U1b0ZjjcKJ8ji3rdo+lHV94DZwLTcT8fXLFV9R1W3Ab8FBrivX4FzhbFanWajm5M+twfoLSKHquo/VPUvmQ4kIl/HOaefptjkVJwfokmqulNVd6tqPp28e3Cuoo7KYh//AvxaVf+sqvtUdR5OED4tYZtZqrpZVXfhXEm1wzn3SlXdoKp/99uxqi5W1VWq2qSqK3F+lIYkbTZVVXep6gqcH76T3NevAKar6jZV3QzMyuK8Z6jqdlXdBLzAgX/LWuCXqvqmqu7AaaK8MkUzVhPQV0SqVPVdVX3dff1fgZ+r6lr3//HPgAEiUpNFucqeBf/4ORqn/d1zm6p2wqmpDQR+ISLnALiB425VPR2n9jUduE9ETsRpvjgiXZuxiJwO9AIedV96GOgnIgN8Nv8P4CwROcnnvVy9l/D4E5yaIThBeHPCexuTPncpTtPPRhFZIiJfTncQETkN55wuU9W/ptisO7Axix/JTH4ACPCqiLwuItek2bYGmOh2SG93f9y745y/Z//3oKrrgQk4P4YfiMijIpK47X4i8iUReUFEtopII87V4hFJm+X7/ftJt6/Ez2/Eqb13Tfyw+yP/Lbec74rIQhE5wX27Brgj4TvahvMdH51FucqeBf8YEZFBOP+xW9Qa1bEa+H847brJ7+9S1btx2kZ7A6/gtL9flOaQo3H+mOpF5D3gz+7ro3z234Bz5XFLLueUo3dxgqCnR1IZlqrqhcDngP8GFqTakYicDDwDXKOqf0xzzM1Ajyw6Vr0O7IMTXvunhLK9p6r/oqpH4dRY70kzwmczTg27U8LtYFV9JGGbZul4VfVhVT0DJyAqzo+xn4dxzru7qlbjXLFJhnPzpP3+c/QOTlkT97UXpxmqGVV9TlW/jtPk8wZOsxQ439O/Jn1PVar6cgHlKhsW/GNARA4VkfNxauAPqeqqFNudgDOU8nX3+QR3OGaViLR1m3wOAV5T1Uacpo67ReQiETlYRCpF5BwRuVVE2uNc5o/FuVT3bjcAtSmC4S+BwThtsMWwABgjIr1F5GDgpoRzP0hEakWkWlX34LQT+w4VFJG+wP8FblDV32Y45qs4QW+GiHQQkfbuFVEzqroVp8N1hIhUuDX7YxKOebmIdHOf/gMnQHvlex+n7dtzLzDOraWLe9zzUg1HFZHjReRMEWmH84PuNQX5OQTYpqq7ReRUYHiG80+0APixiBzmnssNOXw22SPAd0Wkl4h0xGmyeSz5CktEuorIBSLSAafpawcHzm22W54+7rbVInJ5AWUqKxb8o+23IvIxTg1nMk5wvTppmx+4Y/R3As8D9wO/dt/bBfwnzqX3h8B1wKWq+iaAqv4S+B5OR9lW9zjX49SaL3I//6Bba33Pbdufi9MJeXZyYVX1I+BWmvdJBEZVn8W5uvgTTkffn5I2GQlsEJGPcJoJRqTY1USgCzDX/e52iMjrfhu6/SffxBmtswmng/tbKfb7LzgjYBqAPjijdDyDgD+LyA6cmvd3VPUt972bgXlu88UVqrrM3dddOD8U63E6l1Nph9MZ+yHOv/XngJ+k2HY8MM39f/VT0lwd+ZiK0zzzFs7/tfk5fDbZfe7nX3T3txv/H5M2OP9e7+A06wzBOQdU9SmcK5xH3X/z1cA5BZSprHjDrowxxpQRq/kbY0wZsuBvjDFlyIK/McaUIQv+xhhThiKbFOqII47Qnj17hl0MY4yJleXLl3+oql0ybRdI8BeR+3ASUX2gqn193h8KPI0zpAvgSVVNmwqgZ8+eLFu2LIjiGWNM2RCRbGZeB1bzfwBnTPKDabb5H1U9P6DjGWOMKUAgbf6q+iLN880YY4yJsFJ2+H5ZRFaIs1JUH78NRGSsOKtKLdu6dWsJi2aMMeWlVMH/LziLLJyEs/DHf/ttpKpzVHWgqg7s0iVjf4Uxxpg8lST4q+pHbs5uVHURUCkiyWlkjTHGlEhJgr+I/JOIiPv4VPe4DaU4tjHGmJaCGur5CM7ycEeIyBacVLuVAKo6G7gM+LaI7MXJFHmlWkY5Y4wJTSDBX1WvyvD+XThDQY0xxkSApXcwxpgMGhuhTx/nvrWw4G+MMRksXAhr1sCiRWGXJDgW/I0xJoXhw6FjRxg92nk+apTzfHgui19GlAX/Uhg61LkZY2Jl2jTo0QMqK53nlZVQUwO33BJuuYJgwd8YY1I49ljnB2DPHujQwbmfOhWOOSbskhXOgn8xeTX+JUucm10BGBM7CxY4gX/qVOf+8cfDLlEwIpvP3xhjomDSJLjzTujaFUaMgM2bwy5RMCz4F9Pixc69V9v3nhtjYmPQoAOPu3Z1bq2BNfsYY0wZspp/KViN3xgTMVbzN8aYMmTB3xhjypAFf2OMKUMW/I0xpgxZ8M+XTdgyxsSYBX9jjAlQXNI/21DPXHm1/SVLmj+34ZzGGJqnf74q7TJX4bKavzHGBCBu6Z+t5p8rS9lgjPExbRrU18OGDbB3b/TTP1vN3xhjAhC39M8W/PO1eLHV+o0xzcQp/bM1+xTKmn+MMa44pX+24G+MMQGJU/pnC/75siGfxpgYszZ/Y4wpQ1bzz5cN+TTGxJjV/I0xpgwFEvxF5D4R+UBEVqd4X0RkloisF5GVIvLFII4bCTbk0xgTQ0HV/B8Azk7z/jnAce5tLPCrgI5rjDEmD4EEf1V9EdiWZpMLgQfV8b9AJxE5MohjG2OMyV2p2vyPBhKnO2xxX2tGRMaKyDIRWbZ169YSFc0YY8pPqYK/+LymLV5QnaOqA1V1YJcuXUpQLGOMKU+lCv5bgO4Jz7sB75To2MYYY5KUKvg/A4xyR/2cBjSq6rslOrYxxpgkgUzyEpFHgKHAESKyBbgJqARQ1dnAIuBcYD3wCXB1EMc1xhiTn0CCv6qmXaxMVRW4LohjGWOMKZzN8DXGmDJkwT8Khg49kCPIGGNKwIK/McaUIcvqGSZbE8AYExKr+RtjTBmymn++hg6F+noYMCD/mrqtCWCMCYnV/I0xpgxZ8M/V0KHQqZPTTt/Y6Nx36lTYaB1bE8CYkmlshD59nPtyZsHfGFNWFi6ENWtg0aKwSxIuC/65WrwYtm+HIUOgutq5377dau7GRNzw4dCxI4we7TwfNcp5Pnx4uOUKiwX/MNikLmNKbto06NEDKiud55WVUFMDt9wSbrnCYsE/X94VgNX4jYmFY491fgD27IEOHZz7qVPhmGPCLlk4LPiXklfjX7LEudkVgDEltWCBE/inTnXuH3887BKFx8b5G2PKxqRJcOed0LUrjBgBmzdn/kxrZcG/lGxSlymRulV1TP7jZDY1bqJHdQ+mD5tObb/asIsVukGDDjzu2tW5eRobYfBgePllZyxHa2fNPsa0MnWr6hj727FsbNyIomxs3MjY346lblVd2EWLtHIbAirOOivRM3DgQF22bFnYxTAmdnrO7MnGxo0tXq+prmHDhA2lL1DEDR8OzzwDn34Ke/dC27bQrh1ccAE8/HDYpcudiCxX1YGZtrOaf9CsE9eEbFPjppxeL3flOgTUgr8xrUyP6h45vV7uynUIqAX/oNgwThMR04dN5+DKg5u9dnDlwUwfNj2kEkVfOQ4BtdE+xrQy3qgeG+2TvXIcAmodvoXwG7JpwziNMSHKtsPXav5BsSYeY0yMWPDPh9/au4Wu6mWMMSVkHb5BqK8/sLCLdfQaUxJ1q+roObMnbaa2oefMnqFNYovr4jAW/PPhrbzl5fQfMCDsEhlTVqI0izmuM4Otw7cQiZ271tFrTMlEYRZzVGcG2wzfUkhO1GaMKYkozGKO+8zgQIK/iJwtIutEZL2I/Mjn/TEislVE6t3btUEc1xiTu6i0lRciCrOY4z4zuODgLyIVwN3AOUBv4CoR6e2z6WOqOsC9/Vehxw1d8oze+nrnZkyERamtvBBRmcUc55nBQdT8TwXWq+qbqvoZ8ChwYQD7jZfGRudmo31MAIpVO5/8x8l8sueTZq99sucTJv9xciD7L5XafrXM+eYcaqprEISa6hrmfHNOyWcxT5oE69bBxInO/aRJJT18QYIY5380kDgZegvwJZ/tLhWR/wP8FfiuqraYQC0iY4GxAD16RDwJldfe36mTcx+3cV4msrzauRekvdo5UHBwi0JbeSbZLkRT26829JQVqRaHicPCMEHU/MXnteQhRL8Feqpqf+APwDy/HanqHFUdqKoDu3TpEkDRSmDAAOc2ZIhz84aBGpOnYtbOo9BWnk5raZaKw/DPIIL/FqB7wvNuwDuJG6hqg6p+6j69FzglgONGgxfs823zt2Yik6SYtfOotJWnEvdmqeHDoWNHGD3aeT5qlPN8+PBwy+UniOC/FDhORHqJyEHAlcAziRuIyJEJTy8A1gZw3GjxrgCSWXA3OSpm7TwqbeWpxKFZKp04Df8sOPir6l7geuA5nKC+QFVfF5FpInKBu9mNIvK6iKwAbgTGFHrcyMg3j7/l/zcp5Fs7z7aTuLZfLRsmbKDppiY2TNhQcOAPsnM66s1SmcRp+Gcgid1UdRGwKOm1nyY8/jHw4yCOFRt+yd+MyUI++fiL2UmcTtDHnT5serP9QbSapbLhDf+cMsWp8T/+OFx2WdilasnSOwQlOb1DcvAfMqT59snbWSexKUBY6Q6yOW62o3c83vYbGzdSIRXs033UVNfktSBNrscOwtKlTtNP167w/vvOwjADMyZbCE626R0s+AchXUrn5Bp/ph8DY/LQZmobtMUgOxCEppuaQjtu8pUBODX5TP0M+X4u0z4OqjiIQw46hG27trXaFc4st0+p5ZvL34aGmgCE1Vae6bj5jt7J5nOZ+hr89vHZvs9o2NUQ62GkQbHgX4hsOm294J6YBtrmA5g08ulADWsIZ6bjZhq9k+pcs/lcpvkA2YwQitMw0qBZ8M+WF9htVI4pIr+gNvLJkYxfOD7t58IawpnpuOmuDNIF8CCuKLK96onLMNKgWZt/tpIDvjeha/t267Q1gUnVgSoI8y+ZH7v26XRt916nbrKa6hrOPe5cZi+b3aw/IbHNP5s+Dr9j+ynlGgClYG3+QUlu2vFuO3Y4N2MClKoWqmgsmyfSXRmkOteNjRuZt2Jes+AuCKNPGp3VFUWqY3eu6kxlm8pm28dtGGmQbAH3fO3b59x7id22bw+vLKbV6FHdw7c2DM3bu0s9fLEQqRKwpTrXCqloUVtXlEV/W9RsGKggLa4MkgN58rHj9t0VkzX7pJM4hNPz0kvOvRf8vZR9FvxNAOpW1THyyZG+TRreWPdCh0D6HTOMgJiqSShdM03y+94PQL7zAFoja/YpljPOcG7V1c5t+3YL/CYwtf1qGTdwHJKULNer1Qad+CzMLJqpmoRqqmt8t091ReC12cc58Dc2Qp8+pc0MbzV/P16NP/Fforq6+Vh+a+4xRZSqNp7rZK5MtfpUHcydqzrT8aCOoTSP5HpFUOyJbKXw8MNQW+vcX3VVYfuymn+xeTV+G/ppisAv+VrdqjraiP+frF8HaCFj4Rt2NYSWUz/XK4K4JH3zE2YKaAv+fhYvdgL7kCFOjX/IEOe5DeU0IfEC+T7d1+K9VCNWghwLH8RkqFwmr/n9+EV9LYJ8hJkC2oJ/viwlswlINkHRL5CD0w6eqrM3m9z4fgE1lUImQwXRtxD1tQjyEWYKaAv+6XhXAIXU+O1HwaSRbVBMFXibtCll8MtnLHxNdQ2dqzrntD/vPHLNs5N4NRHWWgRR4KWAnjrVuX/88dIc1zp8C5Vpdq/N/jVpZJuKOZ+UzaXKqJnN9uk6qudfMj/w4atxEnQKaOvwLQVvVFCq96xZyGSQ7bKF+bR359tMkuvnCulb6FHdI/br9hZq0CAn8INzX6rc/zbDt1D5pnI2ZStx+GUbaePbiZscLPNZ3cv7XD6151w+l80PWKpcPdOHTWfkkyNz2q8JRusM/sVuakm1RKPf6lzW7GMSJDeR5DJ6J99AXmyp0jR4P2B1q+rS5upJleAtzkM448CafYwpoXSjduI4gmX8wvFs/mhzi9cTf8D8ztnL1QPhrUVQ7lpXzT9TjTyo/adafzeb49uVQFlLN2onbrNUxy8cz6+W/arF6x0qO/Drb/56/w9YpmahfJu0TGFaV/A3JuIyNZHEyZzlc3xf3713d7PAnc05R7VJqzVrXcE/VY08F+lq65muKNIdv9hXJSYWUmXlzKWJI4wsnH7H9OuvgJb9GEGcswmetfkbU0KFzlINIwtnqmOmyjNUIRXNnrfGmbmtgU3y8iTXzIcMce6Dbq+3Gr8pQD6TvYp1zA6VHdi5Z6fv64lt/qa0bJKXMa1QtpPCSnHMnXt2tqjle6+XMguoyY8Ff8/ixc5tyBDn5j3328aTz6xdv/2aVi+XjJbpZJOvJ2ip9l0hFSnb/ctphm5cBRL8ReRsEVknIutF5Ec+77cTkcfc9/8sIj2DOK4xcRBkO30YY+JTHTNV4PfYDN1oKzj4i0gFcDdwDtAbuEpEeidt9s/AP1T1WOB24D8KPW7RZFMzt7w9JgdB5q4Jo/M018VVPEFfjQR19WQcQQz1PBVYr6pvAojIo8CFwJqEbS4EbnYfPwHcJSKiUe1tNiZAQbfThzEmPtUxk4dweoK+GklOi+FdPXllM7kLotnnaCBxfvcW9zXfbVR1L9AItEgaLiJjRWSZiCzbunVrAEUrkmz6B5LZ1UHZyrWdPi413MQrAjgwxDPfq5F0513umT+LIYiav/i8llyjz2YbVHUOMAecoZ6FF82Y8OUyySluNdygrkIynXcYo5xauyBq/luA7gnPuwHvpNpGRNoC1cC2AI4dLusfKFu5rkebbTt9udZwM513GKOcWrsgav5LgeNEpBfwNnAlkLz2/DPAaOAV4DLgT9beb+Iqn9p5tjXkcq3hZjpvSxERvIJr/m4b/vXAc8BaYIGqvi4i00TkAnezuUBnEVkPfA9oMRw0coKqoefTP2AirZi182xruHHpF8hWpvO2FBHBCySxm6ouAhYlvfbThMe7gcuDOJYxYUtXSy006Vo2Ndy49QtkI5vztsyfwbIZvsmyaaMfOhQ6dcrtysBq/K1Gqlrq4VWHFzyZK5sabjZXHnG7MrCafem1rpTOxpRAqloqkDIo5xLEkmu4XiD3rib8kqzBgSuSuF4ZWM2+tKzmnygx46ZfG71X41+yBBobnfvkKwAbzdPqpaqlbtvlP4CtkM5av9QQ4jty+sAVSborg7hdEZjiseBvTB5q+9WyYcIGmm5qYsOEDdT2q817OGKuk5sUbfEDIAgbGzemTL8MB64ASrkWgIkua/aB3FbZGjDAua+vdx7nsn6vadXyGY6Y7+QmRamprtl/JaDunMnk54kqpCKQZinTOljN35iA5NNpmaqJ5jvPfoeeM3v6BnE4sHhLTXVNi238PpMuC2dQcwisSSlerOYPmdf+TbXKl99nrMZf1nLttEwVeBt2NdCwq8H3vcSriWwCd+eqzlzR5wrmLJ/j+wMQxCzZuHYylzOr+RuToyBruLkG3uSriWw/P2/FPN/An8/i8X7nnmn4ad2qOo649QhkqiBThSNuPcKuDEJma/j6SXcF4LX1e1cBHr81f02rk1zDBSeA5jsm3W9/qQhC001NeX8+WYVUMO/ieTkvHu937iOfHOnb3CQI8y+Zz9X/fTV7mvY0e++gioO478L77MogYLaGb1Bs6KZJEHRqB79+gs5VLbKdA/61/OS0yrlo0qacAm+6c0830mnyHye3CPwAn+37rNn31tgIffo496b4LPgn8pvdW1/ffBtvhI83D8By9kRWMTogi5F4LXnY6B3n3JHTUo3e5x+65CHfz+XyY5JOunNPt7xkuu8m8b2FC2HNGli0KOXmJkAW/NOprz8wmcvvh8BEVpDr5ib+iLQR/z+ZIFML55vqINXncv0xSSVd7T5dmdN9Nz2qezB8OHTsCKNHO6+NGuU8H56cG9gEytr8/fi17VdXH7getfb9yEs12ckbIpmtbNrUC2nzL5XxC8fvH+1TIRWMPWUs95x3T077yLe/o25VXdo2/y9V1XLBBbBhA+zaBVVV0KsXPPMMHHNMTkU0WJt/4RKbd6qrD0zuMrEQVPOMXzs30GyGbVXbqtwKV2J1q+qajfbZp/uYt2JezldBhVyR3H/R/c2anzpXdd7f2XvssTBtGuzZAx06OPdTp1rgLzar+WeSOPLHxvDHRr41/+SUzKlSJSSLcu0/qKugYrriCnj+eZgyBW65Bc46Cx57LOxSxZPV/IOSPHnLxEK6DshUckmilixqSy0m9lNkygIaBZMmwbp1MHGicz9pUtglav3Ke4ZvrjV5q/HHhlcDz2VhlVRJ1LIVlWCa7dj/KK1/O2jQgcdduzo3U1zlHfwzsWRtsRZUqoVsZZO9s5BVvrKVqp8ika1/a8qz2Seb1bpMbAQ1nr+QmnA+TUrFSqec7kfMVskynvIM/tmyxdcjL8ig6tdPkI1Csnd6/QRBzm5N9SNWU13TbP0BsEyc5aw8g78F9VYjyHQLyUMZK6Qi42cEaRZMU8k09DTI2a3ZdnaX8mrERE95Bv9c2Y9DZAWdbiEx1cK8i+dR2aYy7fbZNhWl2q7q6acCn92a7Xj8oPMUmXgp7+BvQT328l06MVsiqYd65tJpeu5x57YYNnpw5cFMuwV69IBK9zemshJqapyx7oVIzhcEtGjeKUaeIhMf5R38TezlM54/W5P/OJnP9n3m+14unabeDNvEYaOCMPqk0Uw878Kiz25N1bxzeNXhvttHaQioKR4L/ibW8k05kI1UNeBs2/k9qeYPLPqb08C/YIET+KdOde4ff7ywcmdzfO95sX44TfTZOH8Te7mO589WqvQOQaZCBmc26513OhObRoyAzZtzL2s+x9+2axvzL5lfkrkHJnos+BuTwvRh032zWOaTCjndj0ixZ7emO36xfjhN9JV3s49N7jJpBNGkVLeqjh2f7WjxeimbV4rZL2Liq6DgLyKHi8jvReRv7v1hKbbbJyL17u2ZQo5pTCklj5rJZXKU19HasKuh2eudqzqXdIZtkP0ittRi61FQSmcRuRXYpqozRORHwGGq+kOf7Xaoasdc9l1QSudMOXiSc/bY4iwmB9kuahKHVMq5evhhqK117q+6KuzSGD+lSul8ITDPfTwPuKjA/RkTedlOjmpN4+htqcXWp9Dg31VV3wVw7z+XYrv2IrJMRP5XRFL+QIjIWHe7ZVu3bs29NNkmbLP0DqYA2Qb1ICaglaqZJVMz1rRpxZmMZsKTMfiLyB9EZLXP7cIcjtPDvQwZDswUEd8pLKo6R1UHqurALl265LB7Y4orn0Xcg+hoDTLnTyrZ5PixpRZbn4zBX1W/pqp9fW5PA++LyJEA7v0HKfbxjnv/JrAYODmwM0iUa43eavwmC8nB0VsLN5FfUC+ko7UYzSzjF46n7bS2yFSh7bS2jF84Hsi+GavYk9FMaRXa4fsLoCGhw/dwVf1B0jaHAZ+o6qcicgTwCnChqq5Jt++idvgG/TkTW9kssJKq47ZCKmj/f4kzAAAPiklEQVTSpqJMjlq/Hi64ADZsgF27oKoKevWCZ57Jr7Y9fuF4frXsVy1e//bAbzN72WzfFcsEoemmpv3Ply51mn66doX333cmow3M2K1oSi3bDt9Cg39nYAHQA9gEXK6q20RkIDBOVa8VkcHAr4EmnCuNmao6N9O+Q1nA3YJ/Wcl21E6bqW2yCo5Be+IJZ0RNu3bw6afwyCNw2WX57avttLa+VywVUkG3Q7u1ulFJ5awko31UtUFVh6nqce79Nvf1Zap6rfv4ZVXtp6onufcZA3/J2cpeZSnb5o5iZw5NJZdmlkwdtn6B33vdJoGVp/Ke4WvKWrajdsIKjpMmwbp1MHGicz9pkv922XTYplqYpkIqipocz0RXQc0+xWTNPqbYcpmEVarF1/ORzXmka/O/57x7il1EU0LZNvtYYjdTtnJJ3BblBGjZXMF4AX7O8jns031USAVjTxlrgb+MWfBPZDX+suIF8yBq9GFeGWSbevqe8+6xYG/2szZ/0yplk3gN/BO3ZfvZxGOFuRC6ddiafFjwN61OIcE4n8+GvRC6ddiafFiHr2l1UnWAdq7qTMeDOuY1oSvdmPew5gEY46dUWT2NiZxUHaANuxqa1ehHPjkSmSrNmnbyycQZ1jwAYwphwd+0OtkGXa+2nti0k08gtzZ3E0c22se0On5DODPx2ujzWbc3yFFD5WTPnj1s2bKF3bt3h12UWGrfvj3dunWj0suznSNr8zdF1dgIgwfDyy9DdXXpjps89HLHZztaLKeYzGujj/KErmzF4RzeeustDjnkEDp37oyIhF2cWFFVGhoa+Pjjj+nVq1ez90qS2K2YLPi3DlFZ9s8viVuy1pLILNW5dq7qzB3n3BGZH4G1a9dywgknWODPk6ryxhtvcOKJJzZ73Tp8Taiituxf4nBIcGr5iVpTG73f0FNwOrxLOf8gGxb481fod2fB3xRFFJf98yZ06U3K/Evmt9px8elGJpVy/oGJNgv+piiivuyf38ze1iLTaKc4LiBfLO+99x5XXnklxxxzDL179+bcc8/lr3/9Kxs2bKBv37557fOBBx7gnXfeKahcb7zxBl/+8pdp164dt912W0H7SsWCvymaOC/7l2uKhyjxG3qaKNbzDwJca0NVufjiixk6dCh///vfWbNmDT/72c94//33C9pvPsF/7969zZ4ffvjhzJo1i+9///sFlSUdC/6maLLNRx81YefqKZTXv9G5qnOL91pT30ahXnjhBSorKxk3btz+1wYMGMBXvvKVZts98MADXH/99fufn3/++SxevJh9+/YxZswY+vbtS79+/bj99tt54oknWLZsGbW1tQwYMIBdu3axfPlyhgwZwimnnMJZZ53Fu+++C8DQoUP5yU9+wpAhQ7jjjjuaHfNzn/scgwYNynsYZzZsnL8pmkGDDjzu2tW5xUG6XD1xaR7yUlDHYchnVrza/pIlzZ8XkIl39erVnHLKKXl/vr6+nrfffpvVq1cDsH37djp16sRdd93FbbfdxsCBA9mzZw833HADTz/9NF26dOGxxx5j8uTJ3Hffffs/s8Q7pxKz4G9MknxSPERVlNchiLvPf/7zvPnmm9xwww2cd955fOMb32ixzbp161i9ejVf//rXAdi3bx9HHnnk/ve/9a1vlay8ySz4G5Mk2/z4poS8Gn6Aq+316dOHJ554IuN2bdu2panpQII+b0byYYcdxooVK3juuee4++67WbBgwf4avUdV6dOnD6+88orvvjt06FDAGRTG2vyNSWK5esrDmWeeyaeffsq99967/7WlS5e2aIbp2bMn9fX1NDU1sXnzZl599VUAPvzwQ5qamrj00ku55ZZb+Mtf/gLAIYccwscffwzA8ccfz9atW/cH/z179vD666+X4vQyspq/MUksV0+EBbjanojw1FNPMWHCBGbMmEH79u3p2bMnM2fObLbd6aefTq9evejXrx99+/bli1/8IgBvv/02V1999f6rgp///OcAjBkzhnHjxlFVVcUrr7zCE088wY033khjYyN79+5lwoQJ9OnTJ23Z3nvvPQYOHMhHH31EmzZtmDlzJmvWrOHQQw8N7vwtvYMxJgxr165tkZrA5MbvO7T0DgVobIQ+fZx7Y4xpjSz4+1i4ENasgUWLwi6JMcYUhwX/BFFLRmaMMcViwT9BFJORGWNMMRQU/EXkchF5XUSaRCRlB4OInC0i60RkvYj8qJBjFlPUk5EZY0xQCq35rwYuAV5MtYGIVAB3A+cAvYGrRKR3gcctmjgnI4sbr2N90ybrYDem1AoK/qq6VlXXZdjsVGC9qr6pqp8BjwIXFnLcYoprMrI48jrWb73VOthNOKKa0rmuro7+/fvTv39/Bg8ezIoVKwran59StPkfDWxOeL7Ffa0FERkrIstEZNnWrVtLULSWBg06kICsa1cYmHG0rMmV17E+YoTz/O67nfvaWutgN6kFnWY7yimde/XqxZIlS1i5ciVTpkxh7NixBZXJT8bgLyJ/EJHVPrdsa+9+a435zixT1TmqOlBVB3bp0iXL3Zu48TrWDzqo+evt2lkHu/FXjDTbUU7pPHjwYA477DAATjvtNLZs2ZL3eaaSMb2Dqn6twGNsAbonPO8GFHZNZGLN61i/6ion4H/6qXO/d691sBt/xUizHZeUznPnzuWcc87Ju5yplCK3z1LgOBHpBbwNXAnYhX2Z8zrWa2pg5Uo44QTYsMHpYL/ssrBLZ6Imimm2S5HS+YUXXmDu3Lm89NJLwRaeAoO/iFwM3Al0ARaKSL2qniUiRwH/parnqupeEbkeeA6oAO5T1WiktTOhmTQJ7rzTGelTVQW7d0P37rB5c+bPmvJTjDTbUU/pvHLlSq699lqeffZZOnduuSpboQod7fOUqnZT1Xaq2lVVz3Jff0dVz03YbpGqfkFVj1FVy4tr9nesDxoEffs6HevWwW5SKUaa7SindN60aROXXHIJ8+fP5wtf+ELe55iOpXQ2xkReMdJsRzml87Rp02hoaGD8+PGAc/URdJZjS+lsjAmFpXQunKV0NsYYkxML/sYYU4Ys+BtjTBmy4G9MEdhqcCbqLPgbUwS2GpyJOgv+xgTIVoMzcWHB35gA2Wpw8SIiTJw4cf/z2267jZtvvjntZ2bPns2DDz5Y5JIVnwV/YwJkq8EVV9B9Ke3atePJJ5/kww8/zPoz48aNY9SoUcEUIEQW/I0JmK0GVzxB96W0bduWsWPHcvvtt7d4b+PGjQwbNoz+/fszbNgwNm1yksjdfPPN3HbbbQDMmjWL3r17079/f6688koAdu7cyTXXXMOgQYM4+eSTefrpp4MpbMAs+JtYiNPoGVsNLnjF7Eu57rrrqKurozHpP9f111/PqFGjWLlyJbW1tdx4440tPjtjxgxee+01Vq5cyezZswGYPn06Z555JkuXLuWFF15g0qRJ7Ny5s/CCBsyCv4mFOI2esdXgglfMvpRDDz2UUaNGMWvWrGavv/LKKwx3f11Gjhzpm1a5f//+1NbW8tBDD9G2rZMq7fnnn2fGjBkMGDCAoUOHsnv37v1XDVFiwd9Emo2eMVD8vpQJEyYwd+7ctDV0kZaLEi5cuJDrrruO5cuXc8opp7B3715Uld/85jfU19dTX1/Ppk2bIpnDyIK/iTQbPWM8xexLOfzww7niiiuYO3fu/tcGDx7Mo48+CjgLqp9xxhnNPuOleP7qV7/Krbfeyvbt29mxYwdnnXUWd955J17SzNdeey24ggbIgr+JNBs9YzzF7kuZOHFis1E/s2bN4v7776d///7Mnz+/xTq7+/btY8SIEfTr14+TTz6Z7373u3Tq1IkpU6awZ88e+vfvT9++fZkyZUqwBQ2IpXQ2kXfFFfD88zBlilPjP+sseOyxsEtlCmUpnQtXSEpnW8zFRJ635GPXrjBihC31aEwQLPibyBs06MDjrl0PjKQxxuTP2vyNMaGJarNzHBT63VnwN8aEon379jQ0NNgPQB5UlYaGBtq3b5/3PqzZxxgTim7durFlyxa2bt0adlFiqX379nTr1i3vz1vwN8aEorKykl69eoVdjLJlzT7GGFOGLPgbY0wZsuBvjDFlKLIzfEVkK7CxBIc6Ash+JYfwxKWcYGUtFitrcbS2staoapdMO4ps8C8VEVmWzVTosMWlnGBlLRYra3GUa1mt2ccYY8qQBX9jjClDFvxhTtgFyFJcyglW1mKxshZHWZa17Nv8jTGmHFnN3xhjypAFf2OMKUNlH/xF5BYRWSki9SLyvIgcFXaZUhGRX4jIG255nxKRTmGXKRURuVxEXheRJhGJ5DA6ETlbRNaJyHoR+VHY5UlFRO4TkQ9EZHXYZclERLqLyAsistb99/9O2GVKRUTai8irIrLCLevUsMuUjohUiMhrIvK7IPZX9sEf+IWq9lfVAcDvgJ+GXaA0fg/0VdX+wF+BH4dcnnRWA5cAL4ZdED8iUgHcDZwD9AauEpHe4ZYqpQeAs8MuRJb2AhNV9UTgNOC6CH+vnwJnqupJwADgbBE5LeQypfMdYG1QOyv74K+qHyU87QBEtgdcVZ9X1b3u0/8F8s/nWmSqulZV14VdjjROBdar6puq+hnwKHBhyGXypaovAtvCLkc2VPVdVf2L+/hjnGB1dLil8qeOHe7TSvcWyb9/EekGnAf8V1D7LPvgDyAi00VkM1BLtGv+ia4Bng27EDF2NJC4GvAWIhqk4kpEegInA38OtySpuU0p9cAHwO9VNaplnQn8AGgKaodlEfxF5A8istrndiGAqk5W1e5AHXB9lMvqbjMZ5/K6LrySZlfWCBOf1yJZ64sjEekI/AaYkHR1HSmqus9t8u0GnCoifcMuUzIROR/4QFWXB7nfsljMRVW/luWmDwMLgZuKWJy0MpVVREYD5wPDNORJGjl8r1G0Beie8Lwb8E5IZWlVRKQSJ/DXqeqTYZcnG6q6XUQW4/StRK1j/XTgAhE5F2gPHCoiD6nqiEJ2WhY1/3RE5LiEpxcAb4RVlkxE5Gzgh8AFqvpJ2OWJuaXAcSLSS0QOAq4Engm5TLEnIgLMBdaq6i/DLk86ItLFGzEnIlXA14jg37+q/lhVu6lqT5z/p38qNPCDBX+AGW5TxUrgGzg96lF1F3AI8Ht3aOrssAuUiohcLCJbgC8DC0XkubDLlMjtOL8eeA6nU3KBqr4ebqn8icgjwCvA8SKyRUT+OewypXE6MBI40/0/Wu/WWKPoSOAF929/KU6bfyDDKOPA0jsYY0wZspq/McaUIQv+xhhThiz4G2NMGbLgb4wxZciCvzHGlCEL/sYYU4Ys+BtjTBn6/2nlHEWLBI9nAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Anaconda\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    }
   ],
   "source": [
    "pca = PCA(n_components=2).fit(iris.data)\n",
    "pca_2d = pca.transform(iris.data)\n",
    "for i in range(0, pca_2d.shape[0]):\n",
    "    if dbscan.labels_[i] == 0:\n",
    "        c1 = plt.scatter(pca_2d[i,0],pca_2d[i,1],c='r', marker='+')\n",
    "    elif dbscan.labels_[i] == 1:\n",
    "        c2 = plt.scatter(pca_2d[i,0],pca_2d[i,1],c='g', marker='o')\n",
    "    elif dbscan.labels_[i] == -1:\n",
    "        c3 = plt.scatter(pca_2d[i,0],pca_2d[i,1],c='b', marker='*')\n",
    "plt.legend([c1, c2, c3], ['Cluster 1', 'Cluster 2', 'Noise'])\n",
    "plt.title('DBSCAN finds 2 clusters and noise')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
